--- #YAML:1.0
name:               Config-Validator
version:            0.6
abstract:           schema based configuration validation
author:
    - Lionel Cons <lionel.cons@cern.ch>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    No::Worries:   0.7
    Scalar::Util:  0
    Test::More:    0
    URI::Escape:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
